import React from "react";
import "./globals.css";
import { AuthProvider } from "../contexts/authContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="light">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
