version: '3.4'


networks:
  backend:
  frontend:

services:
    appdb:
        container_name: app-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 8002:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=password@12345# 
        volumes:
          - D:\dados\volumes\sqlserver:/var/opt/mssql/data
        networks:
          - backend
    backend:
        container_name: backendOrganizer
        image: ${DOCKER_REGISTRY-}backend
        build:
          context: .
          dockerfile: BackEnd/Dockerfile
        ports:
          - 8001:8081
          - 8004:8080
        depends_on:
          - appdb
        environment:
          - DB_HOST=appdb
          - DB_NAME=backendOrganizer
          - DB_SA_PASSWORD=password@12345#
          - JWTKey=NovaSenhaDoJWTGuardadaEmUmLugarTotalmenteSeguro
          - JWTIssuer=https://localhost:8081
          - JWTAudience=https://localhost:8003
        networks:
          - backend
          - frontend

    frontend:
        container_name: frontendApp
        build:
          context: ../frontend
          dockerfile: Dockerfile.dev
        ports:
          - "8003:3000"
        volumes:
          - ../frontend:/app
          - /app/node_modules
        networks:
          - frontend
        command: npm run dev



